More nix
nais/unleasherator pull request #121
Opened 2023-05-23 08:38 UTC by Reasonable-Solutions

This is a nix flake that gives us 3 things or so 
1. it builds a docker file for unleasherator, ~49 mb or such `nix build .#docker.<aarch> `
2. it also builds unleasherator, `nix build` 
3. and you get an automatic build environment with a reproducible set of tools for building, testing etc. see #111, no checks needed. Correct environment every time 

downsides: You have to update sha's every now and then.

2023-05-23 08:48 UTC, Reasonable-Solutions commented
> Makefile no work unless u have nix installed? 🤨

have nix installed, and you have to materialized all the stuff from it in your environment, i.e `nix develop` or transparently through [direnv](https://direnv.net/)

I can make it branch depending on what kind of environment it is if you want to have the naked makefile behavior too

2023-05-23 09:00 UTC, Reasonable-Solutions commented
oh, I should also, use the flake in the builder..

2023-05-31 11:30 UTC, x10an14-nav commented
Doesn't build for me on `x86_64-linux`:

<details>
<summary>Bash log of build</summary>

```
-> $ nom build .#docker.x86_64-linux
these 10 derivations will be built:
  /nix/store/nm3gb0q09708fpc3bpmnr7mh1b13jq32-unleasherator.drv
  /nix/store/831yjw37pn847g087pjxqzlspdyvbv89-unleasherator-customisation-layer.drv
  /nix/store/hhiczsms1mvpzgkdriw687s3ji7qkpxa-unleasherator-base.json.drv
  /nix/store/hyq4pl4i23xmw2kl54z22c0vy2vhjnax-closure.drv
  /nix/store/9sqqy75wznf15pmsx5ncqh1ljy6w694c-closure-paths.drv
  /nix/store/bp0f0jv8yddbc50nf45nxavscnrghlb1-unleasherator-conf.json.drv
  /nix/store/mbbbfaxym81qjjcc60r9h5vj9fj90lzh-pythoncheck.sh.drv
  /nix/store/z8fs1107lwdy2a5h1shjgrzn607yrlqc-stream.drv
  /nix/store/yig8q1ka37gmiw66biwbvm9vrpb41rw6-stream-unleasherator.drv
  /nix/store/v1vgqjws61frw51lzfhrw6raxps87vdx-unleasherator.tar.gz.drv
these 16 paths will be fetched (0.85 MiB download, 2.97 MiB unpacked):
  /nix/store/2y2nabl483f2ri15x11b4sv03ds6z15x-make-shell-wrapper-hook
  /nix/store/5wv3rxgc3pnsh5rcq8vhbn9478bgpdxl-jq-1.6-lib
  /nix/store/88596av4s0n3d76283zdyl0l923r8y93-python3.10-pyflakes-3.0.1
  /nix/store/ac7j8g4ba3b6zqbc00pyya5j7bpylk83-python3.10-flake8-6.0.0
  /nix/store/ga59c4cl43652bbxbp6pghzxmm5c2xcs-python3.10-mccabe-0.7.0
  /nix/store/k913qyi8mmhiaibznsb3rd1ihmgcxjin-python3.10-pycodestyle-2.10.0
  /nix/store/mcaq97q726jywjbi7c6b323cvvf36qgp-dash-0.5.12
  /nix/store/r3ic1scj4yc64fqagb51qfyia89mxgm1-die-hook
  /nix/store/r6lzpxf3mi2530lxg9llbdhg1g4gbw9z-jq-1.6-dev
  /nix/store/vkbzqxn1y9jszz3af7f3vw5pf0hz50ya-pigz-2.6
  /nix/store/w5ysgngbdv6xvm0kgbgzyzbk6ylx5fq2-jq-1.6-bin
  /nix/store/x8nq8x6g4r0hncw5wa3p1mshjmyr73fm-oniguruma-6.9.8-lib
  /nix/store/xsm6rb1cy6wcf24yx7jj4rh9r69w0lk5-libedit-20221030-3.1
  /nix/store/zb35c0z8mq53zvp3gs6px6h7fxy8mllm-lndir-1.0.4
  /nix/store/zs39mqfazj1b9s4z77mlajhzl088wa02-getopt-1.1.6
  /nix/store/zxsfb9gaci6689vrryzpd73g44829cj0-fakeroot-1.29
copying path '/nix/store/vkbzqxn1y9jszz3af7f3vw5pf0hz50ya-pigz-2.6' from 'https://cache.nixos.org'
copying path '/nix/store/r3ic1scj4yc64fqagb51qfyia89mxgm1-die-hook' from 'https://cache.nixos.org'
copying path '/nix/store/xsm6rb1cy6wcf24yx7jj4rh9r69w0lk5-libedit-20221030-3.1' from 'https://cache.nixos.org'
copying path '/nix/store/ga59c4cl43652bbxbp6pghzxmm5c2xcs-python3.10-mccabe-0.7.0' from 'https://cache.nixos.org'
copying path '/nix/store/k913qyi8mmhiaibznsb3rd1ihmgcxjin-python3.10-pycodestyle-2.10.0' from 'https://cache.nixos.org'
copying path '/nix/store/88596av4s0n3d76283zdyl0l923r8y93-python3.10-pyflakes-3.0.1' from 'https://cache.nixos.org'
copying path '/nix/store/zs39mqfazj1b9s4z77mlajhzl088wa02-getopt-1.1.6' from 'https://cache.nixos.org'
copying path '/nix/store/zb35c0z8mq53zvp3gs6px6h7fxy8mllm-lndir-1.0.4' from 'https://cache.nixos.org'
copying path '/nix/store/x8nq8x6g4r0hncw5wa3p1mshjmyr73fm-oniguruma-6.9.8-lib' from 'https://cache.nixos.org'
unleasherator> building '/nix/store/nm3gb0q09708fpc3bpmnr7mh1b13jq32-unleasherator.drv'
copying path '/nix/store/mcaq97q726jywjbi7c6b323cvvf36qgp-dash-0.5.12' from 'https://cache.nixos.org'
copying path '/nix/store/2y2nabl483f2ri15x11b4sv03ds6z15x-make-shell-wrapper-hook' from 'https://cache.nixos.org'
copying path '/nix/store/zxsfb9gaci6689vrryzpd73g44829cj0-fakeroot-1.29' from 'https://cache.nixos.org'
unleasherator> unpacking sources
unleasherator> unpacking source archive /nix/store/2ksh0rxcs12av348vfay91kyn5d0jzz3-source
copying path '/nix/store/5wv3rxgc3pnsh5rcq8vhbn9478bgpdxl-jq-1.6-lib' from 'https://cache.nixos.org'
unleasherator> source root is source
copying path '/nix/store/ac7j8g4ba3b6zqbc00pyya5j7bpylk83-python3.10-flake8-6.0.0' from 'https://cache.nixos.org'
unleasherator> patching sources
unleasherator> configuring
copying path '/nix/store/w5ysgngbdv6xvm0kgbgzyzbk6ylx5fq2-jq-1.6-bin' from 'https://cache.nixos.org'
copying path '/nix/store/r6lzpxf3mi2530lxg9llbdhg1g4gbw9z-jq-1.6-dev' from 'https://cache.nixos.org'
pythoncheck.sh> building '/nix/store/mbbbfaxym81qjjcc60r9h5vj9fj90lzh-pythoncheck.sh.drv'
stream> building '/nix/store/z8fs1107lwdy2a5h1shjgrzn607yrlqc-stream.drv'
unleasherator> building
unleasherator> Building subPackage ./api/v1
unleasherator> Building subPackage ./cmd
unleasherator> Building subPackage ./controllers
unleasherator> Building subPackage ./pkg/resources
unleasherator> Building subPackage ./pkg/unleash
unleasherator> Building subPackage ./pkg/utils
unleasherator> running tests
unleasherator> ok       github.com/nais/unleasherator/api/v1    0.007s
unleasherator> Running Suite: Controller Suite - /build/source/controllers
unleasherator> ===========================================================
unleasherator> Random Seed: 1685532369
unleasherator>
unleasherator> Will run 7 of 8 specs
unleasherator> ------------------------------
unleasherator> [BeforeSuite] [FAILED] [3.875 seconds]
unleasherator> [BeforeSuite]
unleasherator> /build/source/controllers/suite_test.go:44
unleasherator>
unleasherator>   Timeline >>
unleasherator>   STEP: bootstrapping test environment @ 05/31/23 11:26:09.999
unleasherator>   2023-05-31T11:26:09Z   DEBUG   controller-runtime.test-env     starting control plane
unleasherator>   2023-05-31T11:26:10Z   ERROR   controller-runtime.test-env     unable to start the controlplane        {"tries": 0, "error": "timeout waiting for process kube-apiserver to start successfully (it may have failed to start, or stopped unexpectedly before becoming ready)"}
unleasherator>   sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).startControlPlane
unleasherator>          /build/source/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go:329
unleasherator>   sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).Start
unleasherator>          /build/source/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go:259
unleasherator>   github.com/nais/unleasherator/controllers.glob..func3
unleasherator>          /build/source/controllers/suite_test.go:60
unleasherator>   github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3
unleasherator>          /build/source/vendor/github.com/onsi/ginkgo/v2/internal/node.go:463
unleasherator>   github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3
unleasherator>          /build/source/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:863
unleasherator>   2023-05-31T11:26:11Z   ERROR   controller-runtime.test-env     unable to start the controlplane        {"tries": 1, "error": "timeout waiting for process kube-apiserver to start successfully (it may have failed to start, or stopped unexpectedly before becoming ready)"}
unleasherator>   sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).startControlPlane
unleasherator>          /build/source/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go:329
unleasherator>   sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).Start
unleasherator>          /build/source/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go:259
unleasherator>   github.com/nais/unleasherator/controllers.glob..func3
unleasherator>          /build/source/controllers/suite_test.go:60
unleasherator>   github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3
unleasherator>          /build/source/vendor/github.com/onsi/ginkgo/v2/internal/node.go:463
unleasherator>   github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3
unleasherator>          /build/source/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:863
unleasherator>   2023-05-31T11:26:11Z   ERROR   controller-runtime.test-env     unable to start the controlplane        {"tries": 2, "error": "timeout waiting for process kube-apiserver to start successfully (it may have failed to start, or stopped unexpectedly before becoming ready)"}
unleasherator>   sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).startControlPlane
unleasherator>          /build/source/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go:329
unleasherator>   sigs.k8s.io/controller-runtime/pkg/envtest.(*Environ [...]

2023-05-31 20:04 UTC, Starefossen requested changes
Deploy missing from github workflow

2025-12-10 21:52 UTC, closed without merging